### PR TITLE
Added lever highlighting

### PR DESCRIPTION
**Pull request by DapperMickie**
Not ready to be used just yet, need to address:
- remove levers overlay once you've made the potion
- pick a random one from the list if none of them are "the best potion"

### CODE REVIEW

**Comment by raiyni** [comment]
Personally, I don't think the plugin needs to track which levers you *should* pull.

With that said,  the ability to highlight them with color and maybe an optional letter should be an option.

**Comment by dan-drews** [comment]
Gave this a shot and it's super nice. I did notice a weird defect where as you zoom in and out, the number of times you need to pull the lever moves

image
image

Not sure if you'd seen that. It's not awful but would be nice if could stay in place

**Comment by BlueSoapTurtle** [comment]
Is this still being worked on?

**Comment by hex-agon** [comment]
Closing as the base plugin already has basic lever highlighting

**Pull request closed without merging**
